/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as SiteIndexRouteImport } from './routes/_site.index'
import { Route as SiteServicesRouteImport } from './routes/_site.services'
import { Route as SiteProjectsRouteImport } from './routes/_site.projects'
import { Route as SiteCoursesRouteImport } from './routes/_site.courses'
import { Route as SiteContactRouteImport } from './routes/_site.contact'
import { Route as SiteCommunityRouteImport } from './routes/_site.community'
import { Route as SiteBlogRouteImport } from './routes/_site.blog'
import { Route as SiteAboutRouteImport } from './routes/_site.about'

const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteServicesRoute = SiteServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => SiteRoute,
} as any)
const SiteProjectsRoute = SiteProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => SiteRoute,
} as any)
const SiteCoursesRoute = SiteCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => SiteRoute,
} as any)
const SiteContactRoute = SiteContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => SiteRoute,
} as any)
const SiteCommunityRoute = SiteCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => SiteRoute,
} as any)
const SiteBlogRoute = SiteBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => SiteRoute,
} as any)
const SiteAboutRoute = SiteAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => SiteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/about': typeof SiteAboutRoute
  '/blog': typeof SiteBlogRoute
  '/community': typeof SiteCommunityRoute
  '/contact': typeof SiteContactRoute
  '/courses': typeof SiteCoursesRoute
  '/projects': typeof SiteProjectsRoute
  '/services': typeof SiteServicesRoute
}
export interface FileRoutesByTo {
  '/about': typeof SiteAboutRoute
  '/blog': typeof SiteBlogRoute
  '/community': typeof SiteCommunityRoute
  '/contact': typeof SiteContactRoute
  '/courses': typeof SiteCoursesRoute
  '/projects': typeof SiteProjectsRoute
  '/services': typeof SiteServicesRoute
  '/': typeof SiteIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_site': typeof SiteRouteWithChildren
  '/_site/about': typeof SiteAboutRoute
  '/_site/blog': typeof SiteBlogRoute
  '/_site/community': typeof SiteCommunityRoute
  '/_site/contact': typeof SiteContactRoute
  '/_site/courses': typeof SiteCoursesRoute
  '/_site/projects': typeof SiteProjectsRoute
  '/_site/services': typeof SiteServicesRoute
  '/_site/': typeof SiteIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/community'
    | '/contact'
    | '/courses'
    | '/projects'
    | '/services'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/blog'
    | '/community'
    | '/contact'
    | '/courses'
    | '/projects'
    | '/services'
    | '/'
  id:
    | '__root__'
    | '/_site'
    | '/_site/about'
    | '/_site/blog'
    | '/_site/community'
    | '/_site/contact'
    | '/_site/courses'
    | '/_site/projects'
    | '/_site/services'
    | '/_site/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiteRoute: typeof SiteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/services': {
      id: '/_site/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof SiteServicesRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/projects': {
      id: '/_site/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof SiteProjectsRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/courses': {
      id: '/_site/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof SiteCoursesRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/contact': {
      id: '/_site/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof SiteContactRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/community': {
      id: '/_site/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof SiteCommunityRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/blog': {
      id: '/_site/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof SiteBlogRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/about': {
      id: '/_site/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof SiteAboutRouteImport
      parentRoute: typeof SiteRoute
    }
  }
}

interface SiteRouteChildren {
  SiteAboutRoute: typeof SiteAboutRoute
  SiteBlogRoute: typeof SiteBlogRoute
  SiteCommunityRoute: typeof SiteCommunityRoute
  SiteContactRoute: typeof SiteContactRoute
  SiteCoursesRoute: typeof SiteCoursesRoute
  SiteProjectsRoute: typeof SiteProjectsRoute
  SiteServicesRoute: typeof SiteServicesRoute
  SiteIndexRoute: typeof SiteIndexRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteAboutRoute: SiteAboutRoute,
  SiteBlogRoute: SiteBlogRoute,
  SiteCommunityRoute: SiteCommunityRoute,
  SiteContactRoute: SiteContactRoute,
  SiteCoursesRoute: SiteCoursesRoute,
  SiteProjectsRoute: SiteProjectsRoute,
  SiteServicesRoute: SiteServicesRoute,
  SiteIndexRoute: SiteIndexRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SiteRoute: SiteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
